version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    build: .
    # ports:
    #   - "5000:5000"
    # volumes:
    #   - ./app:/app

  redis:
    # image: redis:3.2.0
    extends:
      file: common.yml
      service: redis
