version: '2'
services:
  dockerapp:
    extends:
      file: common.yml
      service: dockerapp
    image: reddysainathn/dockerapp
    # build: .
    # ports:
    #   - "5000:5000"
    # volumes:
    #   - ./app:/app

  redis:
    extends:
      file: common.yml
      service: redis
    # image: redis:3.2.0
